name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Examine source code
        run: go vet -v ./...

      - name: Test source code
        run: go test -v -cover ./...

      - name: Build
        run: go build -v ./...
